// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7sVbLZRI-g8JSKR_O98pPhJ2qQRZoLjE',
    appId: '1:1006566816864:web:90b13375f26a4c0993d705',
    messagingSenderId: '1006566816864',
    projectId: 'my-holy-bible-f307d',
    authDomain: 'my-holy-bible-f307d.firebaseapp.com',
    storageBucket: 'my-holy-bible-f307d.appspot.com',
    measurementId: 'G-HKJZ27LCT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqZ1xoNioEXUlh7gZTUONbHN2Lje2e6cg',
    appId: '1:1006566816864:android:7d79bd384278346293d705',
    messagingSenderId: '1006566816864',
    projectId: 'my-holy-bible-f307d',
    storageBucket: 'my-holy-bible-f307d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_908gZmLqfw1zwzVDCNppDI60MvIz3i0',
    appId: '1:1006566816864:ios:1b8559d8e8a6592493d705',
    messagingSenderId: '1006566816864',
    projectId: 'my-holy-bible-f307d',
    storageBucket: 'my-holy-bible-f307d.appspot.com',
    iosClientId: '1006566816864-gikr5ikomnno3d3kfvgkqcu98mtsd9am.apps.googleusercontent.com',
    iosBundleId: 'com.wearepoe.holybible',
  );
}
